// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"helium/ent/connector"
	"helium/ent/receiver"
	"helium/ent/user"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ReceiverCreate is the builder for creating a Receiver entity.
type ReceiverCreate struct {
	config
	mutation *ReceiverMutation
	hooks    []Hook
}

// SetID sets the "id" field.
func (rc *ReceiverCreate) SetID(s string) *ReceiverCreate {
	rc.mutation.SetID(s)
	return rc
}

// SetUserID sets the "user" edge to the User entity by ID.
func (rc *ReceiverCreate) SetUserID(id uuid.UUID) *ReceiverCreate {
	rc.mutation.SetUserID(id)
	return rc
}

// SetUser sets the "user" edge to the User entity.
func (rc *ReceiverCreate) SetUser(u *User) *ReceiverCreate {
	return rc.SetUserID(u.ID)
}

// SetConnectorID sets the "connector" edge to the Connector entity by ID.
func (rc *ReceiverCreate) SetConnectorID(id string) *ReceiverCreate {
	rc.mutation.SetConnectorID(id)
	return rc
}

// SetConnector sets the "connector" edge to the Connector entity.
func (rc *ReceiverCreate) SetConnector(c *Connector) *ReceiverCreate {
	return rc.SetConnectorID(c.ID)
}

// Mutation returns the ReceiverMutation object of the builder.
func (rc *ReceiverCreate) Mutation() *ReceiverMutation {
	return rc.mutation
}

// Save creates the Receiver in the database.
func (rc *ReceiverCreate) Save(ctx context.Context) (*Receiver, error) {
	return withHooks(ctx, rc.sqlSave, rc.mutation, rc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (rc *ReceiverCreate) SaveX(ctx context.Context) *Receiver {
	v, err := rc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rc *ReceiverCreate) Exec(ctx context.Context) error {
	_, err := rc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rc *ReceiverCreate) ExecX(ctx context.Context) {
	if err := rc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rc *ReceiverCreate) check() error {
	if _, ok := rc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "Receiver.user"`)}
	}
	if _, ok := rc.mutation.ConnectorID(); !ok {
		return &ValidationError{Name: "connector", err: errors.New(`ent: missing required edge "Receiver.connector"`)}
	}
	return nil
}

func (rc *ReceiverCreate) sqlSave(ctx context.Context) (*Receiver, error) {
	if err := rc.check(); err != nil {
		return nil, err
	}
	_node, _spec := rc.createSpec()
	if err := sqlgraph.CreateNode(ctx, rc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Receiver.ID type: %T", _spec.ID.Value)
		}
	}
	rc.mutation.id = &_node.ID
	rc.mutation.done = true
	return _node, nil
}

func (rc *ReceiverCreate) createSpec() (*Receiver, *sqlgraph.CreateSpec) {
	var (
		_node = &Receiver{config: rc.config}
		_spec = sqlgraph.NewCreateSpec(receiver.Table, sqlgraph.NewFieldSpec(receiver.FieldID, field.TypeString))
	)
	if id, ok := rc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if nodes := rc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   receiver.UserTable,
			Columns: []string{receiver.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_receivers = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := rc.mutation.ConnectorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   receiver.ConnectorTable,
			Columns: []string{receiver.ConnectorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(connector.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.connector_receivers = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ReceiverCreateBulk is the builder for creating many Receiver entities in bulk.
type ReceiverCreateBulk struct {
	config
	builders []*ReceiverCreate
}

// Save creates the Receiver entities in the database.
func (rcb *ReceiverCreateBulk) Save(ctx context.Context) ([]*Receiver, error) {
	specs := make([]*sqlgraph.CreateSpec, len(rcb.builders))
	nodes := make([]*Receiver, len(rcb.builders))
	mutators := make([]Mutator, len(rcb.builders))
	for i := range rcb.builders {
		func(i int, root context.Context) {
			builder := rcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ReceiverMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, rcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, rcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, rcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (rcb *ReceiverCreateBulk) SaveX(ctx context.Context) []*Receiver {
	v, err := rcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rcb *ReceiverCreateBulk) Exec(ctx context.Context) error {
	_, err := rcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rcb *ReceiverCreateBulk) ExecX(ctx context.Context) {
	if err := rcb.Exec(ctx); err != nil {
		panic(err)
	}
}
