// Code generated by ent, DO NOT EDIT.

package user

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldEmails holds the string denoting the emails field in the database.
	FieldEmails = "emails"
	// FieldForward holds the string denoting the forward field in the database.
	FieldForward = "forward"
	// FieldPaid holds the string denoting the paid field in the database.
	FieldPaid = "paid"
	// FieldCounter holds the string denoting the counter field in the database.
	FieldCounter = "counter"
	// EdgeReceivers holds the string denoting the receivers edge name in mutations.
	EdgeReceivers = "receivers"
	// Table holds the table name of the user in the database.
	Table = "users"
	// ReceiversTable is the table that holds the receivers relation/edge.
	ReceiversTable = "receivers"
	// ReceiversInverseTable is the table name for the Receiver entity.
	// It exists in this package in order to avoid circular dependency with the "receiver" package.
	ReceiversInverseTable = "receivers"
	// ReceiversColumn is the table column denoting the receivers relation/edge.
	ReceiversColumn = "user_receivers"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldEmails,
	FieldForward,
	FieldPaid,
	FieldCounter,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the User queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByForward orders the results by the forward field.
func ByForward(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldForward, opts...).ToFunc()
}

// ByPaid orders the results by the paid field.
func ByPaid(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPaid, opts...).ToFunc()
}

// ByCounter orders the results by the counter field.
func ByCounter(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCounter, opts...).ToFunc()
}

// ByReceiversCount orders the results by receivers count.
func ByReceiversCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newReceiversStep(), opts...)
	}
}

// ByReceivers orders the results by receivers terms.
func ByReceivers(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newReceiversStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newReceiversStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ReceiversInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ReceiversTable, ReceiversColumn),
	)
}
