// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Connector is the predicate function for connector builders.
type Connector func(*sql.Selector)

// Letter is the predicate function for letter builders.
type Letter func(*sql.Selector)

// Receiver is the predicate function for receiver builders.
type Receiver func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
